telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}

time-values:
  course-update-frequency-in-minutes: 2
  notification-frequency-in-millis: 600000

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true